//
// Created by Olcay Taner YILDIZ on 2019-04-20.
//

#ifndef PARSETREE_SEARCHDIRECTIONTYPE_H
#define PARSETREE_SEARCHDIRECTIONTYPE_H

enum class SearchDirectionType{
    LEFT, RIGHT
};

#endif //PARSETREE_SEARCHDIRECTIONTYPE_H
